### ISSUE TITLE
Color management result by CMM may be "-nan(ind)"

### ISSUE THREAD

**Issue by kensukenagashima-eizo** [InternationalColorConsortium/DemoIccMAX#50]
I noticed that when I apply the profile below to CMM, "-nan(ind)" may be returned.

 InputProfile : ICCProfile_sRGB_v5.xml.icc
 OutputProfile : ICCProfile_AdobeRGB_v5.xml.icc

For example, if you input a RGB device value = ( 0, 0, 64) (normalized RGB value = ( 0, 0, 0.2510),
the output will be a normalized RGB value = ( -nan(ind), -nan(ind), 0.2462).

This is because x is slightly negative in the calculation of pow (float x, float y) in the following part, probably because of a calculation error, and it is out of the definition range.
https://github.com/InternationalColorConsortium/DemoIccMAX/blob/79ecb74135ad47bac7d42692905a079839b7e105/IccProfLib/IccMpeBasic.cpp#L498-L499

Before calculating the pow, I think it might be a good idea to include a process such as rounding the range of x to 0-1.
Alternatively, improvements may be needed elsewhere.

I attached the sample code and profiles.
[TestSample.zip](https://github.com/InternationalColorConsortium/DemoIccMAX/files/9163957/TestSample.zip)

Thank you for your contribution.

**Comment by xsscx** [comment]
@kensukenagashima-eizo 
  
Thank you for Reporting this Issue. 

Recently a [Fuzzing Runner](https://github.com/InternationalColorConsortium/DemoIccMAX/blob/master/contrib/Build/cmake/cov/cov_tag_sample.md) completed validating this and other issues. 

The plan is to close out all Issues older than 90 days and add the Reproductions, like this Bug, to the Runners. Runners currently Hosted at URL https://github.com/xsscx/PatchIccMAX/actions. 

The Projected acknowledges and agrees with this Issue and will endeavour to resolve within 180 days. We are working to expand Unit Test Coverage.

## 🧪 ICC Coverage & Unit Testing Sample

## ✅ 1. Tags by Frequency

| Tag                | Occurrences | Notes |
|--------------------|-------------|-------|
| `Curve`            | 2884        | 🔥 Highest frequency — test edge cases (e.g., short/empty/huge curves) |
| `XYZNumber`        | 1237        | 🎯 High occurrence — should be in unit tests for all color conversions |
| `LocalizedText`    | 896         | 📛 Ensure coverage of language variants and unicode edge cases |
| `TableData`        | 699         | 🧮 Exercise large vs small tables |
| `FormulaSegment`   | 642         | 📐 Validate complex function math logic |
| `ParametricCurve`  | 589         | 📈 Must be tested with boundary values and invalid forms |
| `script`           | 568         | ⚠️ Test for execution safety / parser bugs |
| `multiProcessElementType` | 497  | 🧩 Nested elements, should be fuzzed deeply |
| `MatrixElement`    | 463         | ➗ Numerical stability & overflow testing |

**Comment by xsscx** [comment]
# Reproduction

```
Testing/CalcTest [0] [2025-04-25 21:58:24] $ iccApplyNamedCmm -debugcalc rgbExercise8bit.txt 0 1 calcExercizeOps.icc 1
IccProfLib/IccMpeCalc.cpp:4563:37: runtime error: downcast of address 0x6030000055f0 which does not point to an object of type 'CIccMpeCalculator'
0x6030000055f0: note: object is of type 'CIccMpeTintArray'
 00 00 00 00  d0 d1 6d 06 01 00 00 00  00 00 00 00 01 00 02 00  20 56 00 00 30 60 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'CIccMpeTintArray'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:4563:37
IccProfLib/IccTagBasic.cpp:6608:41: runtime error: nan is outside the range of representable values of type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccTagBasic.cpp:6608:41
IccProfLib/IccMpeCalc.cpp:1249:35: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:1249:35
IccProfLib/IccMpeCalc.cpp:1247:35: runtime error: -inf is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:1247:35
IccProfLib/IccMpeCalc.cpp:1195:35: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:1195:35
IccProfLib/IccMpeCalc.cpp:3616:84: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:3616:84
IccProfLib/IccMpeCalc.cpp:3616:57: runtime error: inf is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeCalc.cpp:3616:57
IccProfLib/IccMpeBasic.cpp:1821:43: runtime error: nan is outside the range of representable values of type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccMpeBasic.cpp:1821:43
IccProfLib/IccTagLut.cpp:2480:39: runtime error: nan is outside the range of representable values of type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccTagLut.cpp:2480:39
IccProfLib/IccTagLut.cpp:2481:39: runtime error: nan is outside the range of representable values of type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior IccProfLib/IccTagLut.cpp:2481:39
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27152==ERROR: AddressSanitizer: BUS on unknown address (pc 0x000106551af5 bp 0x7ff7bb704d90 sp 0x7ff7bb704aa0 T0)
==27152==The signal is caused by a READ memory access.
==27152==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x000106551af5 in CIccCLUT::Interp2d(float*, float const*) const IccTagLut.cpp:2510
    #1 0x0001061e9003 in CIccMpeCLUT::Apply(CIccApplyMpe*, float*, float const*) const IccMpeBasic.cpp:5720
    #2 0x00010626c96c in CIccApplyMpe::Apply(float*, float const*) IccTagMPE.h:213
    #3 0x00010626c6b5 in CIccSubCalcApply::Apply(float*, float const*) IccMpeCalc.h:432
    #4 0x00010626be51 in CIccOpDefSubElement::Exec(SIccCalcOp*, SIccOpState&) IccMpeCalc.cpp:374
    #5 0x000106244568 in CIccCalculatorFunc::ApplySequence(CIccApplyMpeCalculator*, unsigned int, SIccCalcOp*) const IccMpeCalc.cpp:3664
    #6 0x000106245424 in CIccCalculatorFunc::Apply(CIccApplyMpeCalculator*) const IccMpeCalc.cpp:3691
    #7 0x00010625c07a in CIccMpeCalculator::Apply(CIccApplyMpe*, float*, float const*) const IccMpeCalc.cpp:4798
    #8 0x00010626c96c in CIccApplyMpe::Apply(float*, float const*) IccTagMPE.h:213
    #9 0x0001065ce4bb in CIccTagMultiProcessElement::Apply(CIccApplyTagMpe*, float*, float const*) const IccTagMPE.cpp:1467
    #10 0x000106085c9d in CIccXformMpe::Apply(CIccApplyXform*, float*, float const*) const IccCmm.cpp:7526
    #11 0x0001060b3143 in CIccApplyNamedColorCmm::Apply(float*, float const*) IccCmm.cpp:9784
    #12 0x0001060a3d28 in CIccCmm::Apply(float*, float const*) IccCmm.cpp:8756
    #13 0x000104804a0a in CIccNamedColorCmm::Apply(float*, float const*) IccCmm.h:1831
    #14 0x0001047ffbd6 in main iccApplyNamedCmm.cpp:535
    #15 0x7ff814a6852f in start+0xbef (dyld:x86_64+0xfffffffffff1f52f)

==27152==Register values:
rax = 0x0000613000000740  rbx = 0x00007ff7bb705220  rcx = 0x0000603400003800  rdx = 0x00000000000000ff
rdi = 0x0000000000000001  rsi = 0x0000603400003800  rbp = 0x00007ff7bb704d90  rsp = 0x00007ff7bb704aa0
 r8 = 0x0000000000000000   r9 = 0x0000624000004000  r10 = 0x00007fffffffff01  r11 = 0x00007fffffffff01
r12 = 0x00007ff7bb709328  r13 = 0x00007ff856a173a0  r14 = 0x0000000000000000  r15 = 0x00007ff7bb7092d0
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS IccTagLut.cpp:2510 in CIccCLUT::Interp2d(float*, float const*) const
==27152==ABORTING
zsh: abort      iccApplyNamedCmm -debugcalc rgbExercise8bit.txt 0 1 calcExercizeOps.icc 1
```
